# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate niri-ipc

Name:           rust-niri-ipc
Version:        26.4.0
Release:        %autorelease
Summary:        Types and helpers for interfacing with the niri Wayland compositor

License:        GPL-3.0-or-later
URL:            https://crates.io/crates/niri-ipc
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Types and helpers for interfacing with the niri Wayland compositor.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
# FIXME: no license files detected
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+clap-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+clap-devel %{_description}

This package contains library source intended for building other packages which
use the "clap" feature of the "%{crate}" crate.

%files       -n %{name}+clap-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+json-schema-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+json-schema-devel %{_description}

This package contains library source intended for building other packages which
use the "json-schema" feature of the "%{crate}" crate.

%files       -n %{name}+json-schema-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
